[package]
name = "mtgdb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
chrono = "0.4.38"
clap = { version = "4.5.16", features = ["derive"] }
rusqlite = "0.32.1"
